---
title: "Demographics"
author: 
date: "Last Updated: 6/21/2020"
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---
```{r packages, echo=FALSE, warning=FALSE, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(knitr)
library(tidyr)
library(kableExtra)
library(stringr)
library(dplyr)
library(descr)
library(magick)
library(tigerstats)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```


```{r ggplot, fig.width=4, fig.height=3, echo = FALSE, message=FALSE}
#testplot
testdata <- read.csv(file = 'Test_Data.csv')
library(ggplot2)
KGender <- ggplot(data = testdata, aes(x=SEAL.C1.DERI.002)) + geom_bar(show.legend=TRUE, fill=c("light blue","light pink"), colour="black")+ labs(caption = "SEAL Test Data", x = "Child Gender", y = "Total Children")
CGRace <- ggplot(data = testdata, aes(x=SEAL.C1.DERI.003)) + geom_bar(show.legend=TRUE, fill=c("pink","light blue","light green", "light yellow"), colour="black")+ labs(caption = "SEAL Test Data", x = "Caregiver Race", y = "Counts")

```

```{r read data, echo=FALSE}
data.raw <- read_excel('Test_Data2.xls')
basic.demo <- data.raw[, c("SEAL.C1.DERI.002", "SEAL.C1.DERI.003", "SEAL.C1.DERI.003.a", "SEAL.C1.DERI.004" , "SEAL.C1.DERI.005" , "SEAL.C1.DERI.008" ,"SEAL.C1.DERI.008.a")] 
gender.demo <- data.raw[, c("SEAL.C1.DERI.002")] 
```

Test of demographic data using SEAL data to date.

  - Working on getting a legend and labels added to charts
  
  - Once charts are good, intend to put basic demographics:
  
      - Gender, Race, Age, Education, Income Level
  
  - Need to call file with source(here), store data outside source folder, and switch from wide to long based on time variable (?), aggregate or gather commands may work...

```{r display data, echo=FALSE}


names(basic.demo) <- c("Childs Gender","Childs Race","Childs Ethnicity","Caregiver Relationship to Child","Primary Language","Caregivers Race","Caregivers Ethnicity")

kable(basic.demo [1:5,], format = 'html', caption = "Demographics: Gender and Race",
      digits = c(0, 0, 0, 0, 0, 0, 0), align = "ccrr") %>%
  kable_styling(full_width = FALSE, position = "left")
```

```{r pressure, echo=FALSE}
plot(gender.demo)
plot(KGender)
plot(CGRace)

```

