---
title: "Recruitment"
author: 
date: "Last Updated: 7/15/2020"
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---
```{r load-packages, echo=FALSE, warning=FALSE, include=FALSE, cache=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(knitr)
options(digits=2)
library(ggpubr)
library(plotly)
library(emmeans)
library(papaja)
library(ggpubr)
library(kableExtra)
library(descr)
library(dplyr)
library(magick)
library(tidyverse)
library(ggformula)
library(lubridate)
library(janitor)
library(plyr)
library(tigerstats)
library(plotrix)
library(RColorBrewer)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```

```{r DK Log variable setup, echo = FALSE, message=FALSE}
#DK Data
DKdata <- read.csv(file = '/Volumes/psy-ctn/psy-ctn/SNAPLab/SNAP Projects/SEAL/rSEAL Data/Wave_1/RedCap/DK_Log/rSEAL_DKLOG_16JUL2020.csv')

Atempt1Date <- as.Date(DKdata$rseal_dklog_026, format = "%m/%d/%Y")
Atempt2Date <- as.Date(DKdata$rseal_dklog_029, format = "%m/%d/%Y")
Atempt3Date <- as.Date(DKdata$rseal_dklog_032, format = "%m/%d/%Y")

DKParsedData <- select (DKdata, rseal_dkid,rseal_dklog_006:rseal_dk_log_complete )
DKParsedData <- as_tibble(DKParsedData)

```


```{r recruitment, echo=FALSE, message=FALSE, warning=FALSE}

Scheduled <-subset(DKParsedData,DKParsedData$rseal_dklog_025 == '4' | DKParsedData$rseal_dklog_028 == '4'| DKParsedData$rseal_dklog_031 == '4' )

ScheduledCount <- nrow(Scheduled)

#Number in DK Log compared to how many contacted so far

Contacted <- subset(DKParsedData, DKParsedData$rseal_dklog_009 == '1' | DKParsedData$rseal_dklog_009 == '0')

ToContact <- nrow(DKParsedData) - nrow(Contacted)

#Relative success rate (Number interested)

Interested <- subset(DKParsedData, DKParsedData$rseal_dklog_009 == '1')

NumInterested <-nrow(Interested)
PercentInterested <- 100*sum(NumInterested, na.rm=T)/nrow(Contacted)
```

<font size = "4"> There are currently <font size="4" color="red"> `r papaja::printnum(ScheduledCount)`</font> participants scheduled for their first visit in Wave 1.</font> 

<font size = "4"> There are currently <font size="4" color="red"> `r ToContact`</font> participants who have yet to be contacted.</font> 

<font size = "4"> Of those who were contacted, <font size="4" color="red"> `r papaja::printnum(PercentInterested)`\% </font>% were interested.</font> 

```{r Attempt Status, fig.width=4, fig.height=4, echo = FALSE, message=FALSE}

#Attempt Statuses

Attempt1 <- table(DKParsedData$rseal_dklog_025)
Attempt1Plot <- barplot(Attempt1, beside = TRUE, main = "Attempt 1 Statuses",
        col = brewer.pal(5,"Set2"), 
        xlab = " ",
        ylab = "Count", legend = c("Contact family","Requested Call Back", "Non-responsive/Disconnected", "Scheduled", "Ineligible"),
        args.legend = list(x="topright", cex=.7),ylim=c(0,20), xaxt = "n")
barlabels(Attempt1Plot, Attempt1)

Attempt2 <- table(DKParsedData$rseal_dklog_028)
Attempt2Plot <- barplot(Attempt2,
        col =c("#66c2a5","#8da0cb"),
        main = "Attempt 2 Statuses",
        xlab = " ",
        ylab = "Count", legend = c("Contact family", "Non-responsive/Disconnected"),
        args.legend = list(x="topright", cex=.7), ylim=c(0,20),
        xaxt = "n")
barlabels(Attempt2Plot, Attempt2)

Attempt3 <- table(DKParsedData$rseal_dklog_031)
Attempt3Plot <- barplot(Attempt3, beside = TRUE, main = "Attempt 3 Statuses",
        col = c("#e78ac3"),
         xlab = " ",
        ylab = "Count", legend = c("Scheduled"),
         args.legend = list(x="topright", cex=.7),ylim=c(0,10), xaxt = "n")
barlabels(Attempt3Plot, Attempt3)
```   

